[package]
name = "leveldb_rs"
version = "0.1.0"
authors = ["Lewin Bormann <lbo@spheniscida.de>"]
publish = false

[dependencies]
crc = "1.2"
integer-encoding = "1.0"
libc = "0.2"
rand = "0.3"

[dev-dependencies]
time-test = "0.2"

[workspace]
members = ["examples/write-a-lot", "examples/leveldb-tool"]
