version: 2
jobs:
    build:
        working_directory: ~/leveldb/
        docker:
            - image: rust:1.20
        environment:
            RUST_BACKTRACE: 1
        steps:
            - checkout
            - restore_cache:
                key: target-dir
            - run: cargo build
            - run: cargo test
            - save_cache:
                key: target-dir
                paths:
                    - ~/leveldb/target

